src/Entity/Fiche.php
<?php

namespace App\Entity;

use App\Repository\FicheRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: FicheRepository::class)]
#[Vich\Uploadable]
class Fiche
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;
    #[Vich\UploadableField(mapping: 'douane', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string')]
    private ?string $imageName = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_cda = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_exportateur = null;

    #[ORM\Column(length: 255)]
    private ?string $nature_marchandise = null;

    #[ORM\Column(length: 255)]
    private ?string $colis_marchandise = null;

    #[ORM\Column(length: 255)]
    private ?string $poidsNet_marchandise = null;

    #[ORM\Column(length: 255)]
    private ?string $conditionnement_marchandise = null;

    #[ORM\Column(length: 255)]
    private ?string $lieuEmpotage_marchandise = null;

    #[ORM\Column(length: 255)]
    private ?string $nconteneurs = null;

    #[ORM\Column(length: 255)]
    private ?string $typeTC = null;

    #[ORM\Column(length: 255)]
    private ?string $nplombs = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $date = null;

    #[ORM\ManyToOne(inversedBy: 'fiches')]
    private ?user $user = null;

    #[ORM\Column]
    private ?bool $statut = null;

    #[ORM\ManyToOne(inversedBy: 'demande')]
    private ?user $cda = null;



    public function __construct()
    {
        $this->date = new \DateTimeImmutable();
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->date = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getNomCda(): ?string
    {
        return $this->nom_cda;
    }

    public function setNomCda(string $nom_cda): self
    {
        $this->nom_cda = $nom_cda;

        return $this;
    }

    public function getNomExportateur(): ?string
    {
        return $this->nom_exportateur;
    }

    public function setNomExportateur(string $nom_exportateur): self
    {
        $this->nom_exportateur = $nom_exportateur;

        return $this;
    }

    public function getNatureMarchandise(): ?string
    {
        return $this->nature_marchandise;
    }

    public function setNatureMarchandise(string $nature_marchandise): self
    {
        $this->nature_marchandise = $nature_marchandise;

        return $this;
    }

    public function getColisMarchandise(): ?string
    {
        return $this->colis_marchandise;
    }

    public function setColisMarchandise(string $colis_marchandise): self
    {
        $this->colis_marchandise = $colis_marchandise;

        return $this;
    }

    public function getPoidsNetMarchandise(): ?string
    {
        return $this->poidsNet_marchandise;
    }

    public function setPoidsNetMarchandise(string $poidsNet_marchandise): self
    {
        $this->poidsNet_marchandise = $poidsNet_marchandise;

        return $this;
    }

    public function getConditionnementMarchandise(): ?string
    {
        return $this->conditionnement_marchandise;
    }

    public function setConditionnementMarchandise(string $conditionnement_marchandise): self
    {
        $this->conditionnement_marchandise = $conditionnement_marchandise;

        return $this;
    }

    public function getLieuEmpotageMarchandise(): ?string
    {
        return $this->lieuEmpotage_marchandise;
    }

    public function setLieuEmpotageMarchandise(string $lieuEmpotage_marchandise): self
    {
        $this->lieuEmpotage_marchandise = $lieuEmpotage_marchandise;

        return $this;
    }

    public function getNconteneurs(): ?string
    {
        return $this->nconteneurs;
    }

    public function setNconteneurs(string $nconteneurs): self
    {
        $this->nconteneurs = $nconteneurs;

        return $this;
    }

    public function getTypeTC(): ?string
    {
        return $this->typeTC;
    }

    public function setTypeTC(string $typeTC): self
    {
        $this->typeTC = $typeTC;

        return $this;
    }

    public function getNplombs(): ?string
    {
        return $this->nplombs;
    }

    public function setNplombs(string $nplombs): self
    {
        $this->nplombs = $nplombs;

        return $this;
    }

    public function getDate(): ?\DateTimeImmutable
    {
        return $this->date;
    }

    public function setDate(\DateTimeImmutable $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function isStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getCda(): ?user
    {
        return $this->cda;
    }

    public function setCda(?user $cda): self
    {
        $this->cda = $cda;

        return $this;
    }
}

src/Form/FicheType.php
<?php

namespace App\Form;

use App\Entity\Fiche;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class FicheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_cda',TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ],
                "label"=>"Nom CDA",
                "label_attr"=>[
                    "class"=>"form-class"
                ]
            ])
            ->add('nom_exportateur',TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ],
                "label"=>"Nom Exporteur",
                "label_attr"=>[
                    "class"=>"form-class"
                ]
            ])
            ->add('nature_marchandise',TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ],
                "label"=>"Nature Marchandise",
                "label_attr"=>[
                    "class"=>"form-class"
                ]
            ])
            ->add('colis_marchandise',TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ],
                "label"=>"Colis Marchandise",
                "label_attr"=>[
                    "class"=>"form-class"
                ]
            ])
            ->add('poidsNet_marchandise',TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ],
                "label"=>"poids Net Marchandise",
                "label_attr"=>[
                    "class"=>"form-class"
                ]
            ])
            ->add('conditionnement_marchandise',TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ],
                "label"=>"Conditionnement Marchandise",
                "label_attr"=>[
                    "class"=>"form-class mt-2"
                ]
            ])
            ->add('lieuEmpotage_marchandise',TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ],
                "label"=>"Lieu Empotage Marchandise",
                "label_attr"=>[
                    "class"=>"form-class mt-2"
                ]
            ])
            ->add('nconteneurs',TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ],
                "label"=>"N° Conteneurs",
                "label_attr"=>[
                    "class"=>"form-class"
                ]
            ])
            ->add('typeTC',TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ],
                "label"=>"Type TC",
                "label_attr"=>[
                    "class"=>"form-class"
                ]
            ])
            ->add('nplombs',TextType::class,[
                "attr"=>[
                    "class"=>"form-control"
                ],
                "label"=>"N° Plombs",
                "label_attr"=>[
                    "class"=>"form-class"
                ]
            ])
            ->add('imageFile',VichImageType::class,[
                "attr"=>[
                    "class"=>"upload"
                ]
            ])
            ->add('Submit',SubmitType::class,[
                "attr"=>[
                    "class"=>"btn btn-success mt-3 mb-3",
                    
                ],
                "label"=>"Envoyer"
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Fiche::class,
        ]);
    }
}

src/Controller/ChefController.php
<?php

namespace App\Controller;

use App\Entity\AgentVisite;
use App\Repository\UserRepository;
use App\Repository\FicheRepository;
use App\Repository\AgentVisiteRepository;
use App\Repository\RapportEmpotageRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;

#[Route('/chef')]
class ChefController extends AbstractController
{
    #[isGranted('ROLE_CHEF')]
    #[Security("is_granted('ROLE_CHEF')")]
    #[Route('/', name: 'chef_Index')]
    public function index(RapportEmpotageRepository $rapport, UserRepository $agent, FicheRepository $ficherepo): Response
    {
        if(!$this->getUser()){
            return $this->redirectToRoute('app_login');
        }
        $nombre = count($rapport->findNbre());
        $nombreAgent = count($agent->findNbre());
        $nombreFiche = count($ficherepo->findNbre());
        $NonEffectue = count($rapport->findNbreNon()) - $nombre;
        $fiches = $ficherepo->countByDate();
        $rapports = $rapport->countByDate();
        $dates = [];
        $ficheCount = [];
        foreach ($fiches as $fiche) {
            $dates[] = $fiche['nbrejour'];
            $ficheCount[] = $fiche['count'];
        }
        $rapports = $rapport->countByDate();
        $datess = [];
        $rapportCount = [];
        foreach ($rapports as $rapport) {
            $datess[] = $rapport['nbrejour'];
            $rapportCount[] = $rapport['count'];
        }
        return $this->render('chef/index.html.twig',[
            "nombre"=> $nombre,
            "nombreAgent"=>$nombreAgent,
            "nombreFiche"=>$nombreFiche,
            "nonEffectue"=> $NonEffectue,
            "date"=>json_encode($dates),
            'nbre'=>json_encode($ficheCount),
            "datess"=>json_encode($datess),
            'nbres'=>json_encode($rapportCount)
        ]);
    }
    #[isGranted('ROLE_CHEF')]
    #[Security("is_granted('ROLE_CHEF')")]
    #[Route('/ListeAgent', name: 'chef_ListeAgent')]
    public function agent(UserRepository $repository): Response
    {
        if(!$this->getUser()){
            return $this->redirectToRoute('app_login');
        }
        $agents = $repository->findAllUserByRoles();
        return $this->render('chef/ListeAgent.html.twig',[
            'agents'=>$agents
        ]);
    }
    #[isGranted('ROLE_CHEF')]
    #[Security("is_granted('ROLE_CHEF')")]
    #[Route('/ListeFicheTraite/{id}', name: 'ListeFicheTraite')]
    public function traite(Request $request, FicheRepository $repository, UserRepository $userRepository): Response
    {
        if(!$this->getUser()){
            return $this->redirectToRoute('app_login');
        }
        $fiches = $repository->findAllFicheEffectueByUser($request->attributes->get('id'));
        $username = $userRepository->findOneBy(["id"=>$request->attributes->get('id')])->getNom();
        return $this->render('chef/ListeFicheTraite.html.twig',[
            'fiches'=>$fiches,
            'username'=>$username
        ]);
    }
    #[isGranted('ROLE_CHEF')]
    #[Security("is_granted('ROLE_CHEF')")]
    #[Route('/ListeFicheNonTraite/{id}', name: 'ListeFicheNonTraite')]
    public function nonTraite(Request $request, FicheRepository $repository, UserRepository $userRepository): Response
    {
        if(!$this->getUser()){
            return $this->redirectToRoute('app_login');
        }
        $fiches = $repository->findAllFicheByUser($request->attributes->get('id'));
        $username = $userRepository->findOneBy(["id"=>$request->attributes->get('id')])->getNom();
        return $this->render('chef/ListeFicheNonTraite.html.twig',[
            'fiches'=>$fiches,
            'username'=>$username
        ]);
    }
    #[isGranted('ROLE_CHEF')]
    #[Security("is_granted('ROLE_CHEF')")]
    #[Route("/rapport/{id}",name:"chef_rapport")]
    public function rapport(Request $request, RapportEmpotageRepository $repository):Response
    {
        if(!$this->getUser()){
            return $this->redirectToRoute('app_login');
        }
        $rapport = $repository->findBy(['id'=>$request->attributes->get('id')]);
        return $this->render('chef/rapport.html.twig',[
            'rapport'=>$rapport
        ]);
    }
}

src/Controller/FicheController.php
<?php

namespace App\Controller;

use App\Entity\Fiche;
use App\Form\Fiche1Type;
use App\Repository\FicheRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/chef/fiche')]
class FicheController extends AbstractController
{
    #[Route('/', name: 'app_fiche_index', methods: ['GET'])]
    public function index(FicheRepository $ficheRepository): Response
    {
        return $this->render('chef/fiche/index.html.twig', [
            'fiches' => $ficheRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_fiche_new', methods: ['GET', 'POST'])]
    public function new(Request $request, FicheRepository $ficheRepository): Response
    {
        $fiche = new Fiche();
        $form = $this->createForm(Fiche1Type::class, $fiche);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ficheRepository->save($fiche, true);

            return $this->redirectToRoute('app_fiche_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('chef/fiche/new.html.twig', [
            'fiche' => $fiche,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_fiche_show', methods: ['GET'])]
    public function show(Fiche $fiche): Response
    {
        return $this->render('chef/fiche/show.html.twig', [
            'fiche' => $fiche,
        ]);
    }
    
    #[Route('/{id}/edit', name: 'app_fiche_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Fiche $fiche, FicheRepository $ficheRepository): Response
    {
        $form = $this->createForm(Fiche1Type::class, $fiche);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ficheRepository->save($fiche, true);

            return $this->redirectToRoute('app_fiche_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('chef/fiche/edit.html.twig', [
            'fiche' => $fiche,
            'form' => $form,²
        ]);
    }

    #[Route('/{id}', name: 'app_fiche_delete', methods: ['POST'])]
    public function delete(Request $request, Fiche $fiche, FicheRepository $ficheRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$fiche->getId(), $request->request->get('_token'))) {
            $ficheRepository->remove($fiche, true);
        }

        return $this->redirectToRoute('app_fiche_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/chef/fiche/_delete_form.html.twig
<form method="post" action="{{ path('app_fiche_delete', {'id': fiche.id}) }}" onsubmit="return confirm('Êtes vous sûr de vouloir supprimer?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ fiche.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/chef/fiche/_form.html.twig
{{ form_start(form) }}
<div class="container mt-5">
		<div class="row">
			<div class="col">
				<p>ministere du budget et du
					<br>
					portefeuille de l'etat
					<br>
					<span class="text-center">----------<span>
							<br>
							direction generale des douanes
							<br><span class="text-center">----------<span><br>
									direction des services douaniers 
															            du port et des services speciaux
									<br>
									sous direction des service
									<br>
									douaniers du port
									<br><span class="text-center">----------<span><br>
											bureau export</p>
									</div>
									<div class="col">
										<img src="{{asset("assets/img/logoDouane.png")}}" class="rounded mx-auto d-block" alt="..." width="80px">
									</div>
									<div class="col">
										<p>republique de côte d'ivoire</p>
										<p>Union - Discipline - Travail</p>
									</div>
								</div>
								{{ form_start(form) }}
								<hr class="mt-0">
								<h5 class="mb-1">Informations personnels</h5>
								<p class="mb-3"></p>
								<div class="row">
									<div class="col">
										{{ form_row(form.nom_cda) }}
									</div>
									<div class="col">
										{{ form_row(form.nom_exportateur) }}
									</div>
								</div>
								<hr class="mt-2">
								<h5 class="mb-1">Informations sur la marchandise</h5>
								<p class="mb-3"></p>
								<div class="row">
									<div class="col">
										{{ form_row(form.nature_marchandise) }}
									</div>
									<div class="col">
										{{ form_row(form.colis_marchandise) }}
									</div>
									<div class="col">
										{{ form_row(form.poidsNet_marchandise) }}
									</div>
								</div>
								<div class="row">
									<div class="col">
										{{ form_row(form.conditionnement_marchandise) }}
									</div>
									<div class="col">
										{{ form_row(form.lieuEmpotage_marchandise) }}
									</div>
								</div>
								<hr class="mt-2">
								<h5 class="mb-1">Informations sur le conteneur</h5>
								<p class="mb-3"></p>
								<div class="row">
									<div class="col">
										{{ form_row(form.nconteneurs) }}
									</div>
									<div class="col">
										{{ form_row(form.typeTC) }}
									</div>
									<div class="col">
										{{ form_row(form.nplombs) }}
									</div>
								</div>
							</div>
							{{ form_end(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/chef/fiche/edit.html.twig
{% extends 'chefdashboardbase.html.twig' %}

{% block title %}Edition Fiche D'empotage{% endblock %}

{% block body %}
    <h1>Edition fiche d'empotage</h1>

    {{ include('chef/fiche/_form.html.twig', {'button_label': 'Modifier'}) }}

    <a href="{{ path('app_fiche_index') }}" class="btn btn-warning">Revenir à la liste</a>

    {{ include('chef/fiche/_delete_form.html.twig') }}
{% endblock %}

templates/chef/fiche/index.html.twig
{% extends 'chefdashboardbase.html.twig' %}

{% block title %}Liste des fiches de demande d'empotage{% endblock %}
{% block stylesheets %}
{{ parent() }}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
{% endblock %}
{% block body %}
    <h3>Liste des fiches de demande d'empotage</h3>

    <table class="table"  id='table1'>
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom cda</th>
                <th>Nom exportateur</th>
                <th>Nature marchandise</th>
                <th>Date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for fiche in fiches %}
            <tr>
                <td>{{ fiche.id }}</td>
                <td>{{ fiche.nomCda }}</td>
                <td>{{ fiche.nomExportateur }}</td>
                <td>{{ fiche.natureMarchandise }}</td>
                <td>{{ fiche.date ? fiche.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_fiche_show', {'id': fiche.id}) }}" class="me-3"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 0 16 16">
  <path d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
  <path d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
</svg></a>
                    <a href="{{ path('app_fiche_edit', {'id': fiche.id}) }}" class="me-3"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="green" class="bi bi-pen" viewBox="0 0 16 16">
  <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"/>
</svg></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">Aucun Enregistrement Trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    
{% endblock %}
{% block script %}
{{ parent() }}

<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script>
	$(document).ready(function () {
    $('#table1').DataTable();
});
</script>
{% endblock %}

templates/chef/fiche/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Fiche{% endblock %}

{% block body %}
    <h1>Create new Fiche</h1>

    {{ include('fiche/_form.html.twig') }}

    <a href="{{ path('app_fiche_index') }}">back to list</a>
{% endblock %}

templates/chef/fiche/show.html.twig
{% extends 'chefdashboardbase.html.twig' %}

{% block title %}Details fiche
{% endblock %}

{% block body %}
	<div class="row mb-3">
		<div class="col-2 mt-4">
			<a href="{{ path('app_fiche_index') }}" class="btn btn-warning">Revenir à la liste</a>
		</div>
		<div class="col-2  mt-4">
			<a href="{{ path('app_fiche_edit', {'id': fiche.id}) }}" class="btn btn-primary">Editer</a>
		</div>
		<div class="col-2 mt-4">
			{{ include('chef/fiche/_delete_form.html.twig') }}
		</div>
	</div>
	<h1>Details Fiche</h1>

	<div class="container mt-5">
		<div class="row">
			<div class="col">
				<p>ministere du budget et du
					<br>
					portefeuille de l'etat
					<br>
					<span class="text-center">----------<span>
							<br>
							direction generale des douanes
							<br><span class="text-center">----------<span><br>
									direction des services douaniers 
																																	            du port et des services speciaux
									<br>
									sous direction des service
									<br>
									douaniers du port
									<br><span class="text-center">----------<span><br>
											bureau export</p>
									</div>
									<div class="col">
										<img src="{{asset("assets/img/logoDouane.png")}}" class="rounded mx-auto d-block" alt="..." width="80px">
									</div>
									<div class="col">
										<p>republique de côte d'ivoire</p>
										<p>Union - Discipline - Travail</p>

									</div>

								</div>

								<hr class="mt-0">
								<h5 class="mb-1">Informations personnels</h5>
								<p class="mb-3"></p>
								<div class="row">
									<div class="col">
										<p class="fs-4">Nom CDA :
											<span class="fs-2 fw-bold">{{ fiche.nomCda }}</p>
										</p>
									</span>

								</div>
								<div class="col">
									<p class="fs-4">Nom Exportateur :
										<span class="fs-2 fw-bold">{{ fiche.nomExportateur }}</span>
									</p>
								</div>
							</div>
							<hr class="mt-2">
							<h5 class="mb-1">Informations sur la marchandise</h5>
							<p class="mb-3"></p>
							<div class="row">
								<div class="col">
									<p class="fs-4">Nature de la marchandise:
										<span class="fs-2 fw-bold">{{ fiche.natureMarchandise }}</span>
									</p>
								</div>
								<div class="col">
									<p class="fs-4">
										Colis marchandise :
										<span class="fs-2 fw-bold">{{ fiche.colisMarchandise }}</span>
									</p>
								</div>
								<div class="col">
									<p class="fs-4">
										Poids Net Marchandise :
										<span class="fs-2 fw-bold">{{ fiche.poidsNetMarchandise }}</span>
									</p>
								</div>
							</div>
							<div class="row">
								<div class="col">
									<p class="fs-4">
										Conditionnement Marchandise :
										<span class="fs-2 fw-bold">{{ fiche.conditionnementMarchandise }}</span>
									</p>
								</div>
								<div class="col">
									<p class="fs-4">
										Lieu Empotage Marchandise :
										<span class="fs-2 fw-bold">{{ fiche.lieuEmpotageMarchandise }}</span>
									</p>
								</div>
							</div>
							<hr class="mt-2">
							<h5 class="mb-1">Informations sur le conteneur</h5>
							<p class="mb-3"></p>
							<div class="row">
								<div class="col">
									<p class="fs-4">
										N° Conteneurs :
										<span class="fs-2 fw-bold">{{ fiche.nconteneurs }}</span>
									</p>
								</div>
								<div class="col">
									<p class="fs-4">
										Type Tc :
										<span class="fs-2 fw-bold">{{ fiche.typeTC }}<span></p>
										</div>
										<div class="col">
											<p class="fs-4">
												N° Plombs :
												<span class="fs-2 fw-bold">{{ fiche.nplombs }}</span>
											</p>
										</div>
									</p>
								</div>
							</div>
<div class="container mt-5">
		<p class="fs-2">Pièce joint</p>
		<img src="{{ vich_uploader_asset(fiche, 'imageFile') }}" width="1200px" height="700px">
	</div>

						{% endblock %}